# Generated by Django 3.1.14 on 2022-05-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32)),
                ('name_kz', models.CharField(max_length=256)),
                ('name_ru', models.CharField(max_length=256)),
                ('code', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniverQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('CN', 'Консультация'), ('DC', 'Документ тапсыру/Подача документов')], default='CN', max_length=6)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('startBreakTime', models.TimeField()),
                ('endBreakTime', models.TimeField()),
                ('places', models.PositiveSmallIntegerField()),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerqueue.university')),
            ],
        ),
    ]
