# Generated by Django 3.1.14 on 2022-05-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fullname', models.CharField(max_length=256)),
                ('n', models.PositiveSmallIntegerField()),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerqueue.univerqueue')),
            ],
        ),
    ]
