# Generated by Django 3.1.14 on 2022-05-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerqueue', '0002_queueplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerqueue.university')),
            ],
        ),
    ]
