# Generated by Django 3.2 on 2022-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerqueue', '0004_auto_20220529_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.CharField(default='none', max_length=512),
        ),
    ]
