# Generated by Django 3.2 on 2022-05-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerqueue', '0005_university_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerqueue.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniverStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('method', models.CharField(choices=[('online', 'Онлайн документ тапсыру'), ('offline', 'Университетке келу'), ('queue', 'Кезекке тұру'), ('none', 'Ешқандай')], default='none', max_length=12)),
                ('color', models.CharField(choices=[('kok', 'Көк'), ('sary', 'Сары'), ('jasyl', 'Жасыл')], max_length=12)),
                ('univer_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univerqueue.univeraction')),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionStep',
        ),
    ]
